export const fallbackCountries = [
    { name: "United Arab Emirates", phoneCode: "+971", code: "AE" },
    { name: "United States", phoneCode: "+1", code: "US" },
    { name: "United Kingdom", phoneCode: "+44", code: "GB" },
    { name: "Saudi Arabia", phoneCode: "+966", code: "SA" },
    { name: "India", phoneCode: "+91", code: "IN" },
    { name: "Pakistan", phoneCode: "+92", code: "PK" },
    { name: "China", phoneCode: "+86", code: "CN" },
    { name: "Germany", phoneCode: "+49", code: "DE" },
    { name: "France", phoneCode: "+33", code: "FR" },
    { name: "Canada", phoneCode: "+1", code: "CA" },
    { name: "Australia", phoneCode: "+61", code: "AU" },
    { name: "Bahrain", phoneCode: "+973", code: "BH" },
    { name: "Kuwait", phoneCode: "+965", code: "KW" },
    { name: "Oman", phoneCode: "+968", code: "OM" },
    { name: "Qatar", phoneCode: "+974", code: "QA" },
    { name: "Egypt", phoneCode: "+20", code: "EG" },
    { name: "Jordan", phoneCode: "+962", code: "JO" },
    { name: "Lebanon", phoneCode: "+961", code: "LB" },
    { name: "Singapore", phoneCode: "+65", code: "SG" },
    { name: "Malaysia", phoneCode: "+60", code: "MY" },
    { name: "Japan", phoneCode: "+81", code: "JP" },
    { name: "South Korea", phoneCode: "+82", code: "KR" },
    { name: "Russia", phoneCode: "+7", code: "RU" },
    { name: "Turkey", phoneCode: "+90", code: "TR" },
    { name: "Italy", phoneCode: "+39", code: "IT" },
    { name: "Spain", phoneCode: "+34", code: "ES" },
    { name: "Netherlands", phoneCode: "+31", code: "NL" },
    { name: "Switzerland", phoneCode: "+41", code: "CH" },
    { name: "Sweden", phoneCode: "+46", code: "SE" },
    { name: "South Africa", phoneCode: "+27", code: "ZA" },
    { name: "Nigeria", phoneCode: "+234", code: "NG" }
];
